### ISSUE TITLE
Excessive SSD wear caused by constant writes

### ISSUE THREAD

**Issue by GlenNicholls** [CyferShepard/Jellystat#115]
# Setup

Docker on unRAID

* Jellystat `1.0.8` (repo `cyfershepard/jellystat`)
  * `/mnt/cache/appdata/jellystat` mounted to `/app/backend/backup-data`
* Postgres `15` (repo `postgres:15`)
  * `/mnt/cache/appdata/postgres-jellystat/data` mounted to `/var/lib/postgresql/data` 
* SSD as cache for Docker appdata (`Samsung 970 Evo Plus`, 600 TBW (Total Bytes Written, in Terabytes) rating)

# The Problem

I'm seeing excessive writes to my SSD for long periods of time caused by Jellystat's Jellyfin sync running immediately after the last one is finished. In my case, I see ~18MBps write for 5 mins, 5 mins of no writes, and this pattern repeats for as long as the Jellystat container is running (ref. explanation screenshots).

It also seems like Jellystat might be re-writing the DB every time. I haven't been able to think of another reason that Jellystat would have the exact same write load signature *every* time the Jellyfin sync runs.

Why is Jellyfin sync happening so often? Jellystat is for statistics, and to my understanding, this happens through the other sync option. Is there something happening in Jellyfin (e.g. monitoring changes to the filesystem) that is causing Jellystat to constantly sync unnecessarily?

# Potential Solutions/Workarounds

* Allow the user to set the sync interval
* Only write Jellyfin/Jellystat differences to the database
* Splitting sync tasks such that the user can define the interval for each sub-task depending on their importance to the user

I check Jellystat frequently for current Sessions. I only use statistics/analytics to determine when to run backups, maintenance windows, and other heavy CPU/GPU processes. I.e. I don't need analytics to be up-to-date and I don't need recently added info as I'm the only one who sees it and I get that through Jellyseerr/Jellyfin.

An HDD for this and the DB is an option, but it will be 4x slower due to parity and lack of turbo write (to avoid spinning up all drives just for analytics). Because of this, IOWAIT will be much more significant considering the sync frequency and amount of writes, so again, HDD isn't an ideal tradeoff considering my use case.

RAM could be an option, but I'm guessing the mounts defined previously would grow over time with the Jellyfin library.

# Explanation

Below is where I noticed the issue. Something is periodically writing for 5min straight every 10min. To confirm Jellystat, I killed the container and circled where I stopped it.

![image](https://github.com/CyferShepard/Jellystat/assets/17171913/bc316c12-cd27-4632-9de8-f46090984589)

After killing Jellystat, I'm not seeing the same periodic load, at all:

![image](https://github.com/CyferShepard/Jellystat/assets/17171913/de72b266-84d3-43a0-ad48-cfef27b04c3d)

![image](https://github.com/CyferShepard/Jellystat/assets/17171913/0a5b5482-ff20-41f2-a7c0-5c08466d7488)

For number's sake with my Jellyfin library, we can basically do `1e-6 * 18 [MB/s] * 86400 [s/day] / 2 = 0.78 [TB/day]` (div by 2 because the duty cycle is ~50%). That's almost 1TB/day which is crazy to me. This didn't seem right, so I checked the logs:

![image](https://github.com/CyferShepard/Jellystat/assets/17171913/91574925-45e5-46b0-9225-aead15607cf3)

Sure enough, Jellyfin sync times seem to align exactly with my IO writes to my SSD. In my case, Jellystat will void a 600 TBW warranty in 769 days (600 / 0.78 = 769 days, or 2.1 years). That's >2x shorter guaranteed lifespan than the 5-year/600 TBW spec from Samsung for this SSD. 

# Outro

It'd be helpful to have an issue template. I tried to organize this the best I could, but feel free to let me know if you need other information.

**Comment by CyferShepard** [comment]
Hi @GlenNicholls , would you mind taking a look at the unstable branch and letting me know if the solution I implemented there solves this issue? Iv added configurable task intervals + task run checks to ensure tasks don't run back to back or even two of the same tasks at the same time

**Comment by GlenNicholls** [comment]
Sure, I'll give it a shot and report back.

**Comment by GlenNicholls** [comment]
Doesn't look like `unstable` fixes the issue.

I'm still seeing ~5min of write activity (and a large spike when container starts), and a sync to sync interval of ~15min:

![image](https://github.com/CyferShepard/Jellystat/assets/17171913/838cfbbe-cda5-44de-bd8b-bef8931017d3)

![image](https://github.com/CyferShepard/Jellystat/assets/17171913/8406f00b-d1f4-4b84-9dfc-a2fda722fc95)

I don't consider the interval and interval runtime problematic. I would expect that the amount of data written from one sync interval to the next would only be the database differences. It seems to me like the database is being completely overwritten every time sync runs which probably explains why I see this intense IO write "heartbeat".

Regarding the container write spike above, that's curious to me. There's probably a good explanation in the code, just interesting as I usually see a read spike when a container starts as the application is picking up where it left off. In this case, it seems like the container is starting over with the database for updating the application instead of using cached information. Probably insignificant, but I haven't been paying close attention to that write spike until now when I had mostly everything else shut down assuming it was some other background process.

**Comment by GlenNicholls** [comment]
On that note, I think there's still some improvement with `unstable`. Below is the 6hr IO write graph and I've outlined where Jellystat was shutdown:

![image](https://github.com/CyferShepard/Jellystat/assets/17171913/647fdff5-28ed-46c2-83ed-b991a6f9a057)

**Comment by CyferShepard** [comment]
So the problem with how I implemented the sync is it syncs everything, regardless of there's a change or not, I'm exploring ways on how to split this so that there's a sync where it only pulls new information, and then the full sync can run every 24hrs for example. Hopefully when that change is through itl help with the IO issue your having

**Comment by GlenNicholls** [comment]
That makes sense. Thank you for the speedy responses! 

I'm going to stop the container for now. However, feel free to ping me if you want a second set of eyes or someone to sanity-check experiments. I'm not close with JS by any means, but still happy to discuss/review ideas.

**Comment by CyferShepard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improved Performance](https://trello.com/c/s92111RP/3-improved-performance)
